version: '3'
services:
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:alpine-3.4-latest
  ports:
   - "80:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
  depends_on:
   - postgres-server
   - zabbix-java-gateway
  deploy:
   resources:
    limits:
     memory: 512M
   restart_policy:
     condition: on-failure
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  env_file:
   - .env_db_pgsql
   - .env_srv
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-server
     - zabbix-server-pgsql
     - zabbix-server-alpine-pgsql
     - zabbix-server-pgsql-alpine
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-web-nginx-pgsql:
  image: zabbix/zabbix-web-nginx-pgsql:alpine-3.4-latest
  ports:
   - "8081:80"
  depends_on:
   - postgres-server
   - zabbix-server
  deploy:
   resources:
    limits:
     memory: 512M
   restart_policy:
     condition: on-failure
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
  env_file:
   - .env_db_pgsql
   - .env_web
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-web-nginx-pgsql
     - zabbix-web-nginx-alpine-pgsql
     - zabbix-web-nginx-pgsql-alpine
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-3.4-latest
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
  depends_on:
   - zabbix-server
  deploy:
   restart_policy:
     condition: on-failure
  env_file:
   - .env_agent
  user: root
  privileged: true
  pid: "host"
  networks:
   zbx_net:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:alpine-3.4-latest
  ports:
   - "10052:10052"
  deploy:
   restart_policy:
     condition: on-failure
  env_file:
   - .env_java
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-java-gateway
     - zabbix-java-gateway-alpine
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "alpine"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:ubuntu-3.4-latest
  ports:
   - "162:162/udp"
  deploy:
   restart_policy:
     condition: on-failure
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-snmptraps
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "ubuntu"

 postgres-server:
  image: postgres:latest
  deploy:
   restart_policy:
     condition: on-failure
  env_file:
   - .env_db_pgsql
  user: root
  networks:
   zbx_net:
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

networks:
  zbx_net:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24

