version: '3'
services:
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:alpine-3.4-latest
  ports:
   - "80:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
  depends_on:
   - postgres-server
#   - zabbix-java-gateway
  deploy:
   restart_policy:
     condition: always
  restart: "always"
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  env_file:
   - .env_db_pgsql
   - .env_srv
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-server
     - zabbix-server-pgsql
     - zabbix-server-alpine-pgsql
     - zabbix-server-pgsql-alpine
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-web-nginx-pgsql:
  image: zabbix/zabbix-web-nginx-pgsql:alpine-3.4-latest
  ports:
   - "8081:80"
  depends_on:
   - postgres-server
   - zabbix-server
  deploy:
   resources:
    limits:
     memory: 512M
   restart_policy:
     condition: always
  restart: "always"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
  env_file:
   - .env_db_pgsql
   - .env_web
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-web-nginx-pgsql
     - zabbix-web-nginx-alpine-pgsql
     - zabbix-web-nginx-pgsql-alpine
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

# zabbix-java-gateway:
#  image: zabbix/zabbix-java-gateway:alpine-3.4-latest
#  ports:
#   - "10052:10052"
#  deploy:
#   restart_policy:
#     condition: always
#  restart: "always"
#  env_file:
#   - .env_java
#  user: root
#  networks:
#   zbx_net:
#    aliases:
#     - zabbix-java-gateway
#     - zabbix-java-gateway-alpine
#  labels:
#   com.zabbix.description: "Zabbix Java Gateway"
#   com.zabbix.company: "Zabbix SIA"
#   com.zabbix.component: "java-gateway"
#   com.zabbix.os: "alpine"

# zabbix-snmptraps:
#  image: zabbix/zabbix-snmptraps:ubuntu-3.4-latest
#  ports:
#   - "162:162/udp"
#  deploy:
#   restart_policy:
#     condition: always
#  restart: "always"
#  user: root
#  networks:
#   zbx_net:
#    aliases:
#     - zabbix-snmptraps
#  labels:
#   com.zabbix.description: "Zabbix snmptraps"
#   com.zabbix.company: "Zabbix SIA"
#   com.zabbix.component: "snmptraps"
#   com.zabbix.os: "ubuntu"

 postgres-server:
  image: postgres:latest
  volumes:
    - /data/database/postgres/bp:/var/lib/postgresql/data
    - ./postgres.conf:/etc/postgresql/postgresql.conf
  deploy:
   restart_policy:
     condition: always
  restart: "always"
  env_file:
   - .env_db_pgsql
  command: postgres -c config_file=/etc/postgresql/postgresql.conf
  user: root
  networks:
   zbx_net:
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

 grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  volumes:
    - /data/database/grafana:/var/lib/grafana
  deploy:
   restart_policy:
     condition: always
  restart: "always"
  env_file:
    - .env_grafana
  networks:
   zbx_net:

networks:
  zbx_net:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24

